# Generated by Django 4.0.4 on 2022-04-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(choices=[(0, 'HB'), (1, 'Hobbit'), (2, 'LOTR'), (3, 'Lord of the Ring')], max_length=36, null=True, unique=True),
        ),
    ]
