# Generated by Django 4.0.4 on 2022-04-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0004_book_cover_book_is_published_book_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
